import { useState } from 'react';
import { LuCopy, LuPlay, LuChevronDown, LuChevronRight, LuFileInput } from 'react-icons/lu';

/**
 * SqlBlock — Collapsible SQL code block with copy, run, and syntax highlighting.
 * Used inside chat messages to display queries generated by the AI agent.
 *
 * Linear UI redesign: all styles in index.css under ai-sql-* classes.
 */
const SqlBlock = ({ sql, onRun, onApplyToFile, defaultExpanded = true }) => {
    const [isExpanded, setIsExpanded] = useState(defaultExpanded);
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(sql);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    const headerClasses = [
        'ai-sql-header',
        isExpanded ? 'ai-sql-header--expanded' : '',
    ].filter(Boolean).join(' ');

    const copyBtnClasses = [
        'ai-sql-btn',
        copied ? 'ai-sql-btn--copied' : '',
    ].filter(Boolean).join(' ');

    return (
        <div className="ai-sql">
            {/* Header */}
            <div
                className={headerClasses}
                onClick={() => setIsExpanded(!isExpanded)}
            >
                <div className="ai-sql-label">
                    {isExpanded ? <LuChevronDown size={12} /> : <LuChevronRight size={12} />}
                    SQL Query
                </div>
                <div className="ai-sql-actions" onClick={e => e.stopPropagation()}>
                    <button
                        className={copyBtnClasses}
                        onClick={handleCopy}
                        title="Copy SQL"
                    >
                        <LuCopy size={11} /> {copied ? 'Copied!' : 'Copy'}
                    </button>
                    {onApplyToFile && (
                        <button
                            className="ai-sql-btn"
                            onClick={() => onApplyToFile(sql)}
                            title="Apply to current file"
                        >
                            <LuFileInput size={11} /> Apply
                        </button>
                    )}
                    {onRun && (
                        <button
                            className="ai-sql-btn ai-sql-btn--accent"
                            onClick={() => onRun(sql)}
                            title="Run in editor"
                        >
                            <LuPlay size={11} /> Run
                        </button>
                    )}
                </div>
            </div>

            {/* Code */}
            {isExpanded && (
                <pre className="ai-sql-code">
                    {sql}
                </pre>
            )}
        </div>
    );
};

export default SqlBlock;
