import { useState } from 'react';
import { LuCopy, LuPlay, LuChevronDown, LuChevronRight } from 'react-icons/lu';

/**
 * SqlBlock — Collapsible SQL code block with copy, run, and syntax highlighting.
 * Used inside chat messages to display queries generated by the AI agent.
 */
const SqlBlock = ({ sql, onRun, defaultExpanded = true }) => {
    const [isExpanded, setIsExpanded] = useState(defaultExpanded);
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(sql);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    return (
        <div style={{
            border: '1px solid var(--border-color)',
            borderRadius: '6px',
            overflow: 'hidden',
            margin: '8px 0',
            backgroundColor: 'var(--input-bg)',
        }}>
            {/* Header */}
            <div
                onClick={() => setIsExpanded(!isExpanded)}
                style={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                    padding: '6px 10px', cursor: 'pointer',
                    backgroundColor: 'var(--sidebar-item-active-bg)',
                    borderBottom: isExpanded ? '1px solid var(--border-color)' : 'none',
                }}
            >
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', color: 'var(--text-muted)', fontWeight: '600' }}>
                    {isExpanded ? <LuChevronDown size={12} /> : <LuChevronRight size={12} />}
                    SQL Query
                </div>
                <div style={{ display: 'flex', gap: '4px' }} onClick={e => e.stopPropagation()}>
                    <button
                        onClick={handleCopy}
                        title="Copy SQL"
                        style={{
                            background: 'none', border: 'none', color: copied ? 'var(--feedback-success-text)' : 'var(--text-muted)',
                            cursor: 'pointer', padding: '2px 4px', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '10px',
                            borderRadius: '3px', transition: 'color 0.2s',
                        }}
                    >
                        <LuCopy size={11} /> {copied ? 'Copied!' : 'Copy'}
                    </button>
                    {onRun && (
                        <button
                            onClick={() => onRun(sql)}
                            title="Run in editor"
                            style={{
                                background: 'none', border: 'none', color: 'var(--accent-color-user)',
                                cursor: 'pointer', padding: '2px 4px', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '10px',
                                borderRadius: '3px',
                            }}
                        >
                            <LuPlay size={11} /> Run
                        </button>
                    )}
                </div>
            </div>

            {/* Code */}
            {isExpanded && (
                <pre style={{
                    margin: 0, padding: '10px 12px',
                    fontSize: '12px', lineHeight: '1.5',
                    color: 'var(--text-active)',
                    fontFamily: "'Cascadia Code', 'Fira Code', 'Consolas', monospace",
                    whiteSpace: 'pre-wrap', wordBreak: 'break-word',
                    overflowX: 'auto', maxHeight: '200px',
                }}>
                    {sql}
                </pre>
            )}
        </div>
    );
};

export default SqlBlock;
