import { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { LuCopy, LuPlay, LuChevronDown, LuChevronRight, LuFileInput, LuFilePlus2 } from 'react-icons/lu';

/**
 * SqlBlock — Collapsible SQL code block with copy, run, and syntax highlighting.
 * Used inside chat messages to display queries generated by the AI agent.
 *
 * Linear UI redesign: all styles in index.css under ai-sql-* classes.
 */
const SqlBlock = ({ sql, onRun, onApplyToFile, onAppendToFile, defaultExpanded = true }) => {
    const [isExpanded, setIsExpanded] = useState(defaultExpanded);
    const [copied, setCopied] = useState(false);
    const [showApplyMenu, setShowApplyMenu] = useState(false);
    const [menuPos, setMenuPos] = useState(null);
    const menuRef = useRef(null);   // the anchor wrap (button)
    const popRef = useRef(null);    // the portalled menu

    const handleCopy = () => {
        navigator.clipboard.writeText(sql);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    };

    const openApplyMenu = () => {
        if (showApplyMenu) { setShowApplyMenu(false); return; }
        // Anchor the menu to the button in viewport space. It renders in a portal
        // on <body>, so `.ai-sql { overflow: hidden }` (and any scroll container)
        // can no longer clip it — the "menu queda escondido" bug.
        const btn = menuRef.current?.querySelector('button');
        if (btn) {
            const r = btn.getBoundingClientRect();
            setMenuPos({ top: r.bottom + 2, right: window.innerWidth - r.right });
        }
        setShowApplyMenu(true);
    };

    // Close dropdown on outside click (anchor OR portalled menu counts as inside)
    useEffect(() => {
        if (!showApplyMenu) return;
        const handleClickOutside = (e) => {
            if (menuRef.current?.contains(e.target)) return;
            if (popRef.current?.contains(e.target)) return;
            setShowApplyMenu(false);
        };
        const closeOnScroll = () => setShowApplyMenu(false);
        document.addEventListener('mousedown', handleClickOutside);
        // Anchored to viewport coords → any scroll would detach it; just close.
        window.addEventListener('scroll', closeOnScroll, true);
        window.addEventListener('resize', closeOnScroll);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
            window.removeEventListener('scroll', closeOnScroll, true);
            window.removeEventListener('resize', closeOnScroll);
        };
    }, [showApplyMenu]);

    const headerClasses = [
        'ai-sql-header',
        isExpanded ? 'ai-sql-header--expanded' : '',
    ].filter(Boolean).join(' ');

    const copyBtnClasses = [
        'ai-sql-btn',
        copied ? 'ai-sql-btn--copied' : '',
    ].filter(Boolean).join(' ');

    const hasApplyOptions = onApplyToFile || onAppendToFile;

    return (
        <div className="ai-sql">
            {/* Header */}
            <div
                className={headerClasses}
                onClick={() => setIsExpanded(!isExpanded)}
            >
                <div className="ai-sql-label">
                    {isExpanded ? <LuChevronDown size={12} /> : <LuChevronRight size={12} />}
                    SQL Query
                </div>
                <div className="ai-sql-actions" onClick={e => e.stopPropagation()}>
                    <button
                        className={copyBtnClasses}
                        onClick={handleCopy}
                        title="Copy SQL"
                    >
                        <LuCopy size={11} /> {copied ? 'Copied!' : 'Copy'}
                    </button>

                    {/* Apply dropdown: Replace or Append */}
                    {hasApplyOptions && (
                        <div className="ai-sql-apply-wrap" ref={menuRef} style={{ position: 'relative', display: 'inline-flex' }}>
                            <button
                                className="ai-sql-btn"
                                onClick={openApplyMenu}
                                title="Apply to editor"
                            >
                                <LuFileInput size={11} />
                                Apply
                                <LuChevronDown size={9} style={{ marginLeft: 2 }} />
                            </button>
                            {showApplyMenu && menuPos && createPortal((
                                <div ref={popRef} style={{
                                    position: 'fixed',
                                    top: menuPos.top,
                                    right: menuPos.right,
                                    background: 'var(--surface-overlay)',
                                    border: '1px solid var(--border-subtle)',
                                    borderRadius: 6,
                                    boxShadow: 'var(--shadow-md)',
                                    zIndex: 10000,
                                    minWidth: 160,
                                    overflow: 'hidden',
                                }}>
                                    {onApplyToFile && (
                                        <button
                                            style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '7px 12px', fontSize: 12, background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-primary)', textAlign: 'left' }}
                                            onMouseEnter={e => e.currentTarget.style.background = 'var(--hover-bg)'}
                                            onMouseLeave={e => e.currentTarget.style.background = 'none'}
                                            onClick={() => { onApplyToFile(sql); setShowApplyMenu(false); }}
                                        >
                                            <LuFileInput size={12} />
                                            Replace file content
                                        </button>
                                    )}
                                    {onAppendToFile && (
                                        <button
                                            style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '7px 12px', fontSize: 12, background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-primary)', textAlign: 'left' }}
                                            onMouseEnter={e => e.currentTarget.style.background = 'var(--hover-bg)'}
                                            onMouseLeave={e => e.currentTarget.style.background = 'none'}
                                            onClick={() => { onAppendToFile(sql); setShowApplyMenu(false); }}
                                        >
                                            <LuFilePlus2 size={12} />
                                            Append to file
                                        </button>
                                    )}
                                </div>
                            ), document.body)}
                        </div>
                    )}

                    {onRun && (
                        <button
                            className="ai-sql-btn ai-sql-btn--accent"
                            onClick={() => onRun(sql)}
                            title="Run in editor"
                        >
                            <LuPlay size={11} /> Run
                        </button>
                    )}
                </div>
            </div>

            {/* Code */}
            {isExpanded && (
                <pre className="ai-sql-code">
                    {sql}
                </pre>
            )}
        </div>
    );
};

export default SqlBlock;
