name: " Reportar un Bug"
description: "Crea un reporte para ayudarnos a mejorar el IDE."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por tomarte el tiempo de reportar este problema! Por favor, llena la mayor cantidad de detalles posible para poder replicarlo y solucionarlo r谩pido.
  - type: input
    id: version
    attributes:
      label: "Versi贸n del IDE"
      description: "驴Qu茅 versi贸n del programa est谩s usando? (Ej. v1.0.0)"
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Sistema Operativo"
      description: "驴En qu茅 sistema ocurri贸 el error?"
      options:
        - Windows (x64)
        - macOS (Apple Silicon - M1/M2/M3)
        - Otro
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Descripci贸n del problema"
      description: "Explica de forma clara y concisa qu茅 fue lo que fall贸."
      placeholder: "Al intentar cargar un archivo CSV de 500MB, la aplicaci贸n se cierra inesperadamente..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducirlo"
      description: "Enumera los pasos exactos para que nosotros tambi茅n podamos ver el error."
      value: |
        1. Abrir el IDE.
        2. Hacer clic en 'Importar Datos'.
        3. Seleccionar el archivo...
        4. Ocurre el error.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Screenshots o Logs (Opcional)"
      description: "Arrastra aqu铆 capturas de pantalla o pega mensajes de error de la consola si los tienes."