name: " Sugerir una nueva funci贸n"
description: "Prop贸n una idea o mejora para el an谩lisis de datos en el IDE."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        隆Nos encantan las nuevas ideas! Ay煤danos a entender qu茅 necesitas y c贸mo mejorar铆a tu flujo de trabajo.
  - type: textarea
    id: problem
    attributes:
      label: "驴Tu sugerencia resuelve alg煤n problema?"
      description: "Explica si esta idea surge de una frustraci贸n o limitaci贸n actual. Ej. 'Siempre me frustra cuando tengo que limpiar nulos y no hay un bot贸n r谩pido...'"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe la soluci贸n que te gustar铆a ver"
      description: "Explica c贸mo funcionar铆a tu idea dentro del IDE."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternativas que has considerado (Opcional)"
      description: "驴Hay alguna otra forma en la que est茅s resolviendo esto actualmente?"
  - type: textarea
    id: context
    attributes:
      label: "Contexto adicional (Opcional)"
      description: "A帽ade cualquier otro detalle, enlaces a herramientas similares o capturas de pantalla."